# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: BUILD_STAGE
  jobs:
  - job: demo
    steps:
      - bash: echo "Stage build"
- stage: RELEASE_C
  variables:
   - name: var
     ${{ if eq(Succeeded(BUILD_STAGE), 'True') }}:
     value: 'True'
  jobs:
  - job: test_0C
    steps:
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: | 
         if [ "$(var)" = "True" ]; then
          echo $(var)
          exit 1
          fi 
          echo "no exit :)"
          echo $
- stage: RELEASE_D
  jobs:
  - job: test_0D
    steps:
     - bash: echo "Stage D"  
    


