# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: BUILD_STAGE
  jobs:
  - job: demo
    steps:
      - bash: echo "Stage build"

- stage: RELEASE-A
  jobs:
  - job: test_01
    steps:
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: |
          condition: in('dependencies.BUILD_STAGE.result', 'Succeeded')
          echo "Stage build"
- stage: RELEASE-B
  jobs:
  - job: test_02
    steps:
     - bash: echo "Stage C"

