# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: BUILD_STAGE
  jobs:
  - job: demo
    steps:
      - bash: echo "Stage build"
 
- stage: PUBLISH_ARTIFACT
  dependsOn: BUILD_STAGE
  jobs:
  - job: Publish_Artifact
    steps:
     - bash: echo "Publish_Artifact BD"   
- stage: DEV_DEPLOYMENT2
  dependsOn: BUILD_STAGE
  jobs:
  - job: Deploy2
    steps:
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: | 
          exit 1 
- stage: Scan_Code
  condition: always()
  dependsOn:
  - BUILD_STAGE
  - DEV_DEPLOYMENT2
  - PUBLISH_ARTIFACT
  variables:
  - name: var
    value: $[or(in(stageDependencies.PUBLISH_ARTIFACT.Publish_Artifact.result, 'Succeeded'),in(stageDependencies.DEV_DEPLOYMENT2.Deploy2.result, 'Succeeded'))]
  jobs:
  - job: test_0C
#    condition: in(stageDependencies.BUILD_STAGE.demo.result, 'Succeeded')
    steps:
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: | 
         if [ "$(var)" = "False" ]; then
          echo $(var)
          exit 1
          fi 
          echo $(var)
          echo "no exit :)"
  - job: test_02
    steps:
     - bash: echo "Stage BD"    
- stage: DEV_DEPLOYMENT
  dependsOn: Scan_Code
  jobs:
  - job: Deploy
    steps:
     - bash: echo "Stage dev" 
# - stage: QA_SIGN_OFF
#   dependsOn: DEV_DEPLOYMENT
#   #        in(stageDependencies.QA1_DEPLOYMENT.Qa1_Deploy.result, 'Succeeded'),
# #        in(StageDependencies.QA2_DEPLOYMENT.Qa2_Deploy.result, 'Succeeded')
# or(in(succeeded('PUBLISH_ARTIFACT'), 'True'),in(succeeded('DEV_DEPLOYMENT2'), 'True'))
#   variables:
#   - name: var
#     value: $[stageDependencies.QA1_DEPLOYMENT.Qa1_Deploy.result]
#   jobs:
#   - deployment: deployProd
#     displayName: QADeployment2
#     environment: OLB-QA
#   - job: QA_check
#     steps:
#      - task: Bash@3
#        inputs:
#         targetType: 'inline'
#         script: | 
#          if [ "$(var)" = "True" ]; then
#           echo $(var)
#           exit 1
#           fi 
#           echo $(var)
#           echo "no exit :)"
#           echo $[stageDependencies.QA1_DEPLOYMENT.Qa1_Deploy.result]
#           echo $(stageDependencies.QA1_DEPLOYMENT.Qa1_Deploy.result)
#           echo $[dependencies.QA1_DEPLOYMENT.Qa1_Deploy.result]
#           echo $(dependencies.QA1_DEPLOYMENT.Qa1_Deploy.result)
#           echo $[dependencies.QA1_DEPLOYMENT.result]
#           echo $(dependencies.QA1_DEPLOYMENT.result)
#           echo $[dependencies.QA1_DEPLOYMENT.result]
#           echo $(dependencies.QA1_DEPLOYMENT.result)
# - stage: QA1_DEPLOYMENT
#   dependsOn: DEV_DEPLOYMENT
#   jobs:
#   - job: Qa1_Deploy
#     steps:
#     - bash: echo "Stage test"

# - stage: QA2_DEPLOYMENT
#   dependsOn: DEV_DEPLOYMENT
#   jobs:
#   - job: Qa2_Deploy
#     steps:
#      - bash: echo "Stage test1"

# # - stage: QA3_DEPLOYMENT
# #   dependsOn: DEV_DEPLOYMENT
# #   jobs:
# #   - job: Qa3_Deploy
# #     steps:
# #      - bash: echo "Stage dev"

# # - stage: QA4_DEPLOYMENT
# #   dependsOn: DEV_DEPLOYMENT
# #   jobs:
# #   - job: Qa4_Deploy
# #     steps:
# #      - bash: echo "Stage dev"

# # - stage: QA5_DEPLOYMENT
# #   dependsOn: DEV_DEPLOYMENT
# #   jobs:
# #   - job: Qa5_Deploy
# #     steps:
# #      - bash: echo "Stage dev"

# - stage: PROD_DEPLOYMENT
#   dependsOn: QA_SIGN_OFF
#   jobs:
#   - job: Deploy
#     steps:
#      - bash: echo "Stage dev"

#   # - job: QA_result_check
#   #   steps:
#   #    - bash: echo $(dependencies.QA1_DEPLOYMENT.result)
#     #  - bash: echo $[stageDependencies.QA2_DEPLOYMENT.Qa2_Deploy.result]
#     #  - bash: echo $[stageDependencies.QA3_DEPLOYMENT.Qa3_Deploy.result]
#     #  - bash: echo $[stageDependencies.QA4_DEPLOYMENT.Qa4_Deploy.result]
#     #  - bash: echo $[stageDependencies.QA5_DEPLOYMENT.Qa5_Deploy.result]
# - stage: SIGNED_OFF
#   jobs:
#   - job: Approve
#     steps:
#      - bash: echo "Stage dev"