parameters:
- name: target_location
  type: string
  default: "."
  
- name: environment
  type: string
  default: "."
  
- name: depends_on
  type: object
  default: []
  
- name: stage_name
  type: string
  default: "."
  
- name: job_name
  type: string
  default: "."
  
stages:
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.depends_on }}
  condition: succeededOrFailed()
  variables:
   - name: var
     value: $[or(
         in(stageDependencies.${{ parameters.depends_on[1] }}.${{ parameters.job_name }}.result, 'Succeeded'),
         in(stageDependencies.${{ parameters.depends_on[2] }}.${{ parameters.job_name }}.result, 'Succeeded'),
         in(stageDependencies.${{ parameters.depends_on[3] }}.${{ parameters.job_name }}.result, 'Succeeded')
         )]
  jobs:
  - deployment: deployProd
  
