# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: BUILD_STAGE
  jobs:
  - job: demo
    steps:
      - bash: echo "Stage build"

- stage: RELEASE_A
  condition: in(succeeded('BUILD_STAGE'), false)
  jobs:
  - job: test_01
    steps:
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: |
          echo BUILD_STAGE2
- stage: RELEASE_B
  jobs:
  - job: test_02
    steps:
     - bash: echo "Stage C"

